name: Save Client Log

on:
  push:
    branches:
      - main

jobs:
  save-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask requests

    - name: Run app.py
      run: |
        python app.py

    - name: Save client log to GitHub
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add CADASTRO/clientes.csv
        git commit -m 'Atualizando cadastro de clientes'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
